### ISSUE TITLE
invalid value listing subscriptions

### ISSUE THREAD

**Issue by normanr** [nickelc/modiom#2]
```
$ modiom subs list
error decoding response body: invalid value: integer `811`, expected u8 at line 1 column 169
```

(side-note: I can't get `search` to return anything either)

This is compiled from source using the v0.4.0 branch under Termux (aarch64 Android if it makes any difference)

**Comment by nickelc** [comment]
I've updated it to the current `modio` version. That should fix this deserialization issue.

**Comment by normanr** [comment]
`modiom search --game-id 1` still fails with `'Mismatch between definition and access of 'game-id'. Could not downcast to TypeId`

(as does `modiom info 1 1`)

**Comment by nickelc** [comment]
oh sorry, I forgot to update the argument parsing for the ID types.

**Comment by normanr** [comment]
also `upload` fails with `error: invalid value 'test.zip' for '<FILE>': File is not a zip.`.  if I comment out the `path.ends_with(".zip")` check, then it then also gives `` 'Mismatch between definition and access of `game`. Could not downcast to TypeId ``

**Comment by normanr** [comment]
The latest commit works much better for `search` and `info`, `download` still needs fixing though.

**Comment by normanr** [comment]
(also the `install` command seems to be undocumented, even if the Manifest format _is_)

**Comment by nickelc** [comment]
Thank you very much for the testing.

This project is on the back burner for a while and I didn't test every when I refactored & updated its dependencies.

> (also the `install` command seems to be undocumented, even if the Manifest format _is_)

The manifest format & install command is not finished. 
The idea behind it was to support modding communities for games without a mod.io integration.

**Comment by normanr** [comment]
`upload` now works. `download` needs https://github.com/nickelc/modiom/blob/545eeb028132c481f13fc7b60771eae2dfb014b6/src/bin/modiom/commands/download.rs#L42 to be commented out or removed.

**Comment by nickelc** [comment]
Thanks, I removed the line.

**Comment by normanr** [comment]
Thanks! That seems to work, at least as far as I can tell.
